/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.mycompany.voting_system;

import java.awt.EventQueue;
import java.awt.List;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import main.java.com.mycompany.voting_system.k_select_party;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.DefaultButtonModel;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.Marshaller.Listener;
import main.java.com.mycompany.voting_system.z_lastpage;


/**
 *
 * @author USER
 */
public class l_select_candidate extends javax.swing.JFrame {

    /**
     * Creates new form slt_candidate
     */
    //String voternam ;  
    //public slt_candidate(String vvname) {
        //initComponents();
        //voternam = vvname ;
        //partynamee.setText(voternam);


    //}
    
    public l_select_candidate(String vvname) {
        initComponents();
        String voternam ;
        voternam = vvname ;
        partynamee.setText(voternam);
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
            String query = "Select candidate_name from candidate_reg where party_name =? limit 10";
            PreparedStatement pstd =conn.prepareStatement(query);
            pstd.setString(1,partynamee.getText());
            ResultSet results = pstd.executeQuery();
            ArrayList<String> rs = new ArrayList<>();
            while (results.next()){
                //bl1.setText(rs.add(results.getString(1)));
                rs.add(results.getString(1));
            }
                jCheckBox1.setText(rs.get(0));
                jCheckBox2.setText(rs.get(1));
                jCheckBox3.setText(rs.get(2));
                jCheckBox4.setText(rs.get(3));
                jCheckBox5.setText(rs.get(4));
                jCheckBox6.setText(rs.get(5));
                jCheckBox7.setText(rs.get(6));
                jCheckBox8.setText(rs.get(7));
                jCheckBox9.setText(rs.get(8));
                jCheckBox10.setText(rs.get(9));
            
        }
        catch(Exception g){
            JOptionPane.showMessageDialog(null, g);
        }
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        partynamee = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        partynamee.setFont(new java.awt.Font("Times New Roman", 1, 46)); // NOI18N
        partynamee.setForeground(new java.awt.Color(255, 255, 255));
        partynamee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        partynamee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        partynamee.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                partynameeComponentAdded(evt);
            }
        });

        jCheckBox8.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox9.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox10.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jCheckBox10.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox2.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox4.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox5.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox6.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox7.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT CANDIDATE/S");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("X");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("_");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Vote");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Skip");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Instruction");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(107, 107, 107)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCheckBox7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                    .addComponent(jCheckBox4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCheckBox10, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(partynamee, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(partynamee, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        k_select_party e=new k_select_party();
        e.show();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.setState(JFrame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int total_count = 0;

        
        if(jCheckBox1.isSelected()){
            total_count++;
        }if(jCheckBox2.isSelected()){
            total_count++;
        }if(jCheckBox3.isSelected()){
            total_count++;
        }if(jCheckBox4.isSelected()){
            total_count++;
        }if(jCheckBox5.isSelected()){
            total_count++;
        }if(jCheckBox6.isSelected()){
            total_count++;
        }if(jCheckBox7.isSelected()){
            total_count++;
        }if(jCheckBox8.isSelected()){
            total_count++;
        }if(jCheckBox9.isSelected()){
            total_count++;
        }if(jCheckBox10.isSelected()){
            total_count++;
        }if(total_count > 3){
           
            JOptionPane.showMessageDialog(null, "You can only vote for a maximum of three candidates.");
            
        
        }else{
        
        
                if(jCheckBox1.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partynamee.getText());
                    pstd.setString(2, jCheckBox1.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, jCheckBox1.getText());
                        pstr.setString(3, partynamee.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                }   if(jCheckBox2.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partynamee.getText());
                    pstd.setString(2, jCheckBox2.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, jCheckBox2.getText());
                        pstr.setString(3, partynamee.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                } if(jCheckBox3.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partynamee.getText());
                    pstd.setString(2, jCheckBox3.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, jCheckBox3.getText());
                        pstr.setString(3, partynamee.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                }   if(jCheckBox4.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partynamee.getText());
                    pstd.setString(2, jCheckBox4.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, jCheckBox4.getText());
                        pstr.setString(3, partynamee.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                } if(jCheckBox5.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partynamee.getText());
                    pstd.setString(2, jCheckBox5.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, jCheckBox5.getText());
                        pstr.setString(3, partynamee.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                }   if(jCheckBox6.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partynamee.getText());
                    pstd.setString(2, jCheckBox6.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, jCheckBox6.getText());
                        pstr.setString(3, partynamee.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                } if(jCheckBox7.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partynamee.getText());
                    pstd.setString(2, jCheckBox7.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, jCheckBox7.getText());
                        pstr.setString(3, partynamee.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                }   if(jCheckBox8.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partynamee.getText());
                    pstd.setString(2, jCheckBox8.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, jCheckBox8.getText());
                        pstr.setString(3, partynamee.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }



                } if(jCheckBox9.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partynamee.getText());
                    pstd.setString(2, jCheckBox9.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, jCheckBox9.getText());
                        pstr.setString(3, partynamee.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                }   if(jCheckBox10.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partynamee.getText());
                    pstd.setString(2, jCheckBox10.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, jCheckBox10.getText());
                        pstr.setString(3, partynamee.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }
                    }
            
            
        } 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void partynameeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_partynameeComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_partynameeComponentAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int dialogButton = JOptionPane.YES_NO_OPTION;
        dialogButton = JOptionPane.showConfirmDialog (null, "Are you sure?","Select Candidates", dialogButton);
        if(dialogButton == JOptionPane.YES_OPTION) {
                try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
            String query = "Select votes from party_reg where party_name =? ";
            PreparedStatement pstd =conn.prepareStatement(query);
            pstd.setString(1,partynamee.getText());
            ResultSet results = pstd.executeQuery();
            if (results.next()){
                String ss = results.getString(1);
                int b = Integer.parseInt(ss);
                int vl = b + 1 ;
                String sqll = "UPDATE party_reg SET votes=? where party_name =? " ;
                PreparedStatement pstr =conn.prepareStatement(sqll);
                //pstr.setString(1, partynamee.getText());
                pstr.setInt(1, vl);
                pstr.setString(2, partynamee.getText());
                pstr.executeUpdate();
                z_lastpage votee = new z_lastpage();
                votee.show();
                this.hide();
            }

            
            }
            catch(Exception g){
                JOptionPane.showMessageDialog(null, g);
            }
                
        if(dialogButton == JOptionPane.NO_OPTION) {
            remove(dialogButton);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        zz_instruction ins = new zz_instruction();
        ins.show();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(l_select_candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(l_select_candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(l_select_candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(l_select_candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new slt_candidate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel partynamee;
    // End of variables declaration//GEN-END:variables
}
