/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.mycompany.voting_system;


import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import main.java.com.mycompany.voting_system.f_voter_login;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;

/**
 *
 * @author USER
 */
public class k_select_party extends javax.swing.JFrame {

    /**
     * Creates new form select_party
     */
    public k_select_party() {
        initComponents();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
            String query = "Select party_name from party_reg limit 4";
            PreparedStatement pstd =conn.prepareStatement(query);
            ResultSet results = pstd.executeQuery();
            ArrayList<String> rs = new ArrayList<>();
            
            while (results.next()){
                rs.add(results.getString(1));
                
                
            }
                party1.setText(rs.get(0));
                party2.setText(rs.get(1));
                party3.setText(rs.get(2));
                party4.setText(rs.get(3));
            
            //String query1 = "Select images from party_reg ";
            //PreparedStatement pst =conn.prepareStatement(query1);
            //ResultSet result = pst.executeQuery();
            //ArrayList<byte[]> rs1 = new ArrayList<>();
            //while (result.next()){
                //rs1.add(result.getByte(1));
                //rs1.add(result.toByteArray());
            //}
               //byte[] value=rs1.get(0);
               //byte[] valu=rs1.get(1);
               //byte[] val=rs1.get(2);
               //byte[] va=rs1.get(3);
               //lbl_img.setbytes(rs1.get(0));
               //lbl_img1.setText(rs1.get(1));
               //lbl_img2.setText(rs1.get(2));
               //lbl_img3.setText(rs1.get(3));
               
            
            //String query1 = "SELECT images FROM party_reg WHERE name='"+party1+" ' ";
            //PreparedStatement pst =conn.prepareStatement(query1);
            //ResultSet rs1 = pst.executeQuery(query1);
            //while (rs1.next())
            //{
                //BufferedImage im = ImageIO.read(rs.set("images"));
                    //lbl_img.setIcon(new ImageIcon(im));               
            //}            
            
        }
        catch(Exception g){
            JOptionPane.showMessageDialog(null, g);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        party1 = new javax.swing.JRadioButton();
        party2 = new javax.swing.JRadioButton();
        party3 = new javax.swing.JRadioButton();
        party4 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_img = new javax.swing.JLabel();
        lbl_img1 = new javax.swing.JLabel();
        lbl_img2 = new javax.swing.JLabel();
        lbl_img3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Instruction");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        party1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(party1);
        party1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        party1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                party1ActionPerformed(evt);
            }
        });

        party2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(party2);
        party2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        party2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                party2ActionPerformed(evt);
            }
        });

        party3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(party3);
        party3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        party3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                party3ActionPerformed(evt);
            }
        });

        party4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(party4);
        party4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        party4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                party4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Vote");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT A PARTY");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("X");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("_");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SLFP.jpg"))); // NOI18N
        lbl_img.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        lbl_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SLPP.jpg"))); // NOI18N
        lbl_img1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        lbl_img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JVP.jpg"))); // NOI18N
        lbl_img2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        lbl_img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UNP.jpg"))); // NOI18N
        lbl_img3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture7.png"))); // NOI18N

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Instruction");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_img1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_img2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_img3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(party1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(party2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(party3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(party4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(225, 225, 225)))
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(350, 350, 350))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(243, 243, 243))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_img1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_img2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_img3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(party1)
                    .addComponent(party2)
                    .addComponent(party3)
                    .addComponent(party4))
                .addGap(26, 26, 26)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void party1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_party1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_party1ActionPerformed

    private void party4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_party4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_party4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (party1.isSelected()){
            String partyname1 = party1.getText();
            l_select_candidate votee = new l_select_candidate(partyname1);
            votee.show();
            this.hide();
            
            try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from party_reg where party_name =?";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,party1.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE party_reg SET votes=? where party_name = 'SLFP' " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.executeUpdate();
                    }
            }
        
            catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }
            
        } else if(party2.isSelected()){
            l_select_candidate votet = new l_select_candidate(party2.getText());
            votet.show();        // TODO add your handling code here:
            this.dispose();
            try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from party_reg where party_name =?";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,party2.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE party_reg SET votes=? where party_name = 'SLPP' " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.executeUpdate();
                    }
            }
        
            catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }
        } else if (party3.isSelected()){
            l_select_candidate votey = new l_select_candidate(party3.getText());
            votey.show();        // TODO add your handling code here:
            this.hide();
            try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from party_reg where party_name =?";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,party3.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE party_reg SET votes=? where party_name = 'JVP' " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.executeUpdate();
                    }
            }
        
            catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }
        } else if (party4.isSelected()){
            l_select_candidate voe = new l_select_candidate(party4.getText());
            voe.show();        // TODO add your handling code here:
            this.hide();
            try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from party_reg where party_name =?";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,party4.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE party_reg SET votes=? where party_name = 'UNP' " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.executeUpdate();
                    }
            }
        
            catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }
        }
         
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void party2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_party2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_party2ActionPerformed

    private void party3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_party3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_party3ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.setState(JFrame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        zz_instruction ins = new zz_instruction();
        ins.show();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        zz_instruction ins = new zz_instruction();
        ins.show();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(k_select_party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(k_select_party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(k_select_party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(k_select_party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new k_select_party().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_img1;
    private javax.swing.JLabel lbl_img2;
    private javax.swing.JLabel lbl_img3;
    private javax.swing.JRadioButton party1;
    private javax.swing.JRadioButton party2;
    private javax.swing.JRadioButton party3;
    private javax.swing.JRadioButton party4;
    // End of variables declaration//GEN-END:variables
}
