/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.mycompany.voting_system;

import java.awt.EventQueue;
import java.awt.List;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import main.java.com.mycompany.voting_system.k_select_party;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.DefaultButtonModel;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.Marshaller.Listener;
import main.java.com.mycompany.voting_system.z_lastpage;


/**
 *
 * @author USER
 */
public class l_select_candidate extends javax.swing.JFrame {

    /**
     * Creates new form slt_candidate
     */
    //String voternam ;  
    //public slt_candidate(String vvname) {
        //initComponents();
        //voternam = vvname ;
        //partynamee.setText(voternam);


    //}
    
    public l_select_candidate(String partyname1) {
        initComponents();
        //String voternam ;
        //voternam = partyname1 ;
        partyname99.setText(partyname1);
        //System.out.print(partyname1);
        String partyname98 = partyname1.toLowerCase();
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
            String query = "Select candidate_name from candidate_reg where party_name = ? limit 10";
            PreparedStatement pstd =conn.prepareStatement(query);
            pstd.setString(1,partyname98);
            ResultSet results = pstd.executeQuery();
            
            ArrayList<String> rs = new ArrayList<>();
            
            while (results.next()){
                //bl1.setText(rs.add(results.getString(1)));
                rs.add(results.getString("candidate_name"));
            }
            
                 mycheckbox0.setText(rs.get(0));
                 mycheckbox1.setText(rs.get(1));
                 mycheckbox2.setText(rs.get(2));
                 mycheckbox3.setText(rs.get(3));
                 mycheckbox4.setText(rs.get(4));
                 mycheckbox5.setText(rs.get(5));
                 mycheckbox6.setText(rs.get(6));
                 mycheckbox7.setText(rs.get(7));
                 mycheckbox8.setText(rs.get(8));
                 mycheckbox9.setText(rs.get(9));

        }
        catch(Exception g){
            JOptionPane.showMessageDialog(null, g);
        }
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        partyname99 = new javax.swing.JLabel();
        mycheckbox0 = new javax.swing.JCheckBox();
        mycheckbox1 = new javax.swing.JCheckBox();
        mycheckbox2 = new javax.swing.JCheckBox();
        mycheckbox3 = new javax.swing.JCheckBox();
        mycheckbox4 = new javax.swing.JCheckBox();
        mycheckbox5 = new javax.swing.JCheckBox();
        mycheckbox6 = new javax.swing.JCheckBox();
        mycheckbox7 = new javax.swing.JCheckBox();
        mycheckbox8 = new javax.swing.JCheckBox();
        mycheckbox9 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT CANDIDATE/S");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("X");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("_");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Vote");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Skip");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Instruction");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        partyname99.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        mycheckbox0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mycheckbox0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycheckbox0ActionPerformed(evt);
            }
        });

        mycheckbox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mycheckbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycheckbox1ActionPerformed(evt);
            }
        });

        mycheckbox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mycheckbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycheckbox2ActionPerformed(evt);
            }
        });

        mycheckbox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mycheckbox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycheckbox3ActionPerformed(evt);
            }
        });

        mycheckbox4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mycheckbox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycheckbox4ActionPerformed(evt);
            }
        });

        mycheckbox5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mycheckbox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycheckbox5ActionPerformed(evt);
            }
        });

        mycheckbox6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mycheckbox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycheckbox6ActionPerformed(evt);
            }
        });

        mycheckbox7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mycheckbox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycheckbox7ActionPerformed(evt);
            }
        });

        mycheckbox8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mycheckbox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycheckbox8ActionPerformed(evt);
            }
        });

        mycheckbox9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mycheckbox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycheckbox9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(107, 107, 107)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mycheckbox4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mycheckbox3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mycheckbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mycheckbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mycheckbox0, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mycheckbox9, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mycheckbox8, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mycheckbox6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mycheckbox7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mycheckbox5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(partyname99, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 62, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(partyname99, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mycheckbox0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mycheckbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mycheckbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mycheckbox3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mycheckbox4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mycheckbox5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mycheckbox6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mycheckbox7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mycheckbox8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mycheckbox9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.setState(JFrame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int total_count = 0;

        
        if(mycheckbox0.isSelected()){
            total_count++;
        }if(mycheckbox1.isSelected()){
            total_count++;
        }if(mycheckbox2.isSelected()){
            total_count++;
        }if(mycheckbox3.isSelected()){
            total_count++;
        }if(mycheckbox4.isSelected()){
            total_count++;
        }if(mycheckbox5.isSelected()){
            total_count++;
        }if(mycheckbox6.isSelected()){
            total_count++;
        }if(mycheckbox7.isSelected()){
            total_count++;
        }if(mycheckbox8.isSelected()){
            total_count++;
        }if(mycheckbox9.isSelected()){
            total_count++;
        }if(total_count > 3){
           
            JOptionPane.showMessageDialog(null, "You can only vote for a maximum of three candidates.");
            
        
        }else{
        
        
                if(mycheckbox0.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partyname99.getText());
                    pstd.setString(2, mycheckbox0.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, mycheckbox0.getText());
                        pstr.setString(3, partyname99.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                }   if(mycheckbox1.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partyname99.getText());
                    pstd.setString(2, mycheckbox1.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, mycheckbox1.getText());
                        pstr.setString(3, partyname99.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                } if(mycheckbox2.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partyname99.getText());
                    pstd.setString(2, mycheckbox2.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, mycheckbox2.getText());
                        pstr.setString(3, partyname99.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                }   if(mycheckbox3.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partyname99.getText());
                    pstd.setString(2, mycheckbox3.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, mycheckbox3.getText());
                        pstr.setString(3, partyname99.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                } if(mycheckbox4.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partyname99.getText());
                    pstd.setString(2, mycheckbox4.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, mycheckbox4.getText());
                        pstr.setString(3, partyname99.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                }   if(mycheckbox5.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partyname99.getText());
                    pstd.setString(2, mycheckbox5.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, mycheckbox5.getText());
                        pstr.setString(3, partyname99.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                } if(mycheckbox6.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partyname99.getText());
                    pstd.setString(2, mycheckbox6.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, mycheckbox6.getText());
                        pstr.setString(3, partyname99.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                }   if(mycheckbox7.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partyname99.getText());
                    pstd.setString(2, mycheckbox7.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, mycheckbox7.getText());
                        pstr.setString(3, partyname99.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }



                } if(mycheckbox8.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partyname99.getText());
                    pstd.setString(2, mycheckbox8.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, mycheckbox8.getText());
                        pstr.setString(3, partyname99.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }


                }   if(mycheckbox9.isSelected()){

                    try{

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
                    String query = "Select votes from candidate_reg where party_name =? AND candidate_name=? ";
                    PreparedStatement pstd =conn.prepareStatement(query);
                    pstd.setString(1,partyname99.getText());
                    pstd.setString(2, mycheckbox9.getText());
                    ResultSet results = pstd.executeQuery();
                    if (results.next()){
                        String ss = results.getString(1);
                        int b = Integer.parseInt(ss);
                        int vl = b + 1 ;
                        String sqll = "UPDATE candidate_reg SET votes=? where candidate_name =? AND party_name=? " ;
                        PreparedStatement pstr =conn.prepareStatement(sqll);
                        pstr.setInt(1, vl);
                        pstr.setString(2, mycheckbox9.getText());
                        pstr.setString(3, partyname99.getText());
                        pstr.executeUpdate();
                        z_lastpage votee = new z_lastpage();
                        votee.show();
                        this.hide();
                    }


                    }
                    catch(Exception g){
                        JOptionPane.showMessageDialog(null, g);
                    }
                    }
            
            
        } 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int dialogButton = JOptionPane.YES_NO_OPTION;
        dialogButton = JOptionPane.showConfirmDialog (null, "Are you sure?","Select Candidates", dialogButton);
        if(dialogButton == JOptionPane.YES_OPTION) {
                try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/slems", "", "");
            String query = "Select votes from party_reg where party_name =? ";
            PreparedStatement pstd =conn.prepareStatement(query);
            pstd.setString(1,partyname99.getText());
            ResultSet results = pstd.executeQuery();
            if (results.next()){
                String ss = results.getString(1);
                int b = Integer.parseInt(ss);
                int vl = b + 1 ;
                String sqll = "UPDATE party_reg SET votes=? where party_name =? " ;
                PreparedStatement pstr =conn.prepareStatement(sqll);
                pstr.setString(1, partyname99.getText());
                pstr.setInt(1, vl);
                pstr.setString(2, partyname99.getText());
                pstr.executeUpdate();
                z_lastpage votee = new z_lastpage();
                votee.show();
                this.hide();
            }

            
            }
            catch(Exception g){
                JOptionPane.showMessageDialog(null, g);
            }
                
        if(dialogButton == JOptionPane.NO_OPTION) {
            remove(dialogButton);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        zz_instruction ins = new zz_instruction();
        ins.show();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mycheckbox0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycheckbox0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mycheckbox0ActionPerformed

    private void mycheckbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycheckbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mycheckbox1ActionPerformed

    private void mycheckbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycheckbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mycheckbox2ActionPerformed

    private void mycheckbox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycheckbox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mycheckbox3ActionPerformed

    private void mycheckbox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycheckbox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mycheckbox4ActionPerformed

    private void mycheckbox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycheckbox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mycheckbox5ActionPerformed

    private void mycheckbox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycheckbox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mycheckbox6ActionPerformed

    private void mycheckbox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycheckbox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mycheckbox7ActionPerformed

    private void mycheckbox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycheckbox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mycheckbox8ActionPerformed

    private void mycheckbox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycheckbox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mycheckbox9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(l_select_candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(l_select_candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(l_select_candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(l_select_candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new slt_candidate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox mycheckbox0;
    private javax.swing.JCheckBox mycheckbox1;
    private javax.swing.JCheckBox mycheckbox2;
    private javax.swing.JCheckBox mycheckbox3;
    private javax.swing.JCheckBox mycheckbox4;
    private javax.swing.JCheckBox mycheckbox5;
    private javax.swing.JCheckBox mycheckbox6;
    private javax.swing.JCheckBox mycheckbox7;
    private javax.swing.JCheckBox mycheckbox8;
    private javax.swing.JCheckBox mycheckbox9;
    private javax.swing.JLabel partyname99;
    // End of variables declaration//GEN-END:variables
}
